name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# When a Push is made on an existing branch/PR,
# it cancells any pre running job and
# let only the latest executing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}


jobs:
  pulp-docs-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-python@v3
      - name: Test pulp-docs
        run: |
          pip install git+https://github.com/pedro-psb/pulp-docs.git
          pulp-docs build

